os: osx
osx_image: xcode9.1
language: cpp
install:
  - export PATH=$PATH:$PWD/depot_tools
  - gclient config https://chromium.googlesource.com/external/webrtc --unmanaged --name=src
  - travis_wait 30 gclient sync -j8
script:
  - cd src
  - gn gen out/Release --args='rtc_include_tests=false rtc_enable_protobuf=false use_rtti=true enable_iterator_debugging=false is_debug=false'
  - ninja -C out/Release webrtc
  - cd ..
  - "find src -name '*.a' -o -name '*.h' -exec tar -rf webrtc-mac.tar {} \\;"
  - bzip2 webrtc-mac.tar
addons:
  artifacts:
    paths:
       - webrtc-mac.tar.bz2
