version: '{build}'

image: 'Visual Studio 2017'

environment:
  GYP_MSVS_VERSION: 2017
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  matrix:
      - IS_DEBUG: 'true'
      - IS_DEBUG: 'false'
matrix:
    exclude:
        - configuration: Debug
          IS_DEBUG: 'false'
        - configuration: Release
          IS_DEBUG: 'true'

configuration:
  - Debug
  - Release

clone_folder: c:\projects\webrtc


init:
- git config --global core.autocrlf input


# After checkout.
install:
  - git submodule update --init --recursive
  - misc_tools\patch -p0 -i windows-dynamic-runtime.patch
  - PATH C:\projects\webrtc\depot_tools;%PATH%
  - gclient config https://chromium.googlesource.com/external/webrtc --unmanaged --name=src
  - gclient sync -j8

build_script:
  - cd src
  - gn gen out/Default --args="rtc_include_tests=false rtc_enable_protobuf=false use_rtti=true enable_iterator_debugging=false is_component_build=true is_debug=%IS_DEBUG% target_cpu=\"x86\""
  - ninja -C out/Default webrtc
  - cd ..
  - 7z a webrtc-win.7z -r *.h *.lib

artifacts:
  - path: webrtc-win.7z
    name: webrtc-win.7z

test: off
